
back_end_brokins:
    resource: "@BackEndBrokinsBundle/Resources/config/routing.yml"
    type: rest
    prefix: /api





admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

api_login_check:
    path: /api/login_check

