back_end_brokins_comparatif:
    resource: "@BackEndBrokinsBundle/Controller/ComparatifController.php"
    type:     annotation

comparatif:
    resource: "@ComparatifBundle/Resources/config/routing.yml"
    prefix:   /


back_end_brokins:
    resource: "@BackEndBrokinsBundle/Resources/config/routing.yml"
    type: rest
    prefix: /api

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

user:
    resource: "@BackEndBrokinsBundle/Resources/config/routing.yml"


