
# app/config/security.yml
security:
    encoders:
       FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_SUSPECT:        ROLE_SUSPECT
        ROLE_PROSPECT:       ROLE_PROSPECT
        ROLE_CLIENT:        ROLE_CLIENT
        ROLE_ADMIN:        ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:

        api:
            pattern:   ^/api
            stateless: true
            form_login:
                provider: fos_userbundle
                check_path:               api_fos_user_security_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

            logout:       true
            anonymous:    true

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                csrf_token_generator: security.csrf.token_manager
                success_handler: login_success_handler
            logout:
                path:   /logout
                target: /login
            anonymous:    true

    access_control:
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, role: [ROLE_ADMIN,ROLE_USER,ROLE_SUSPECT,ROLE_PROSPECT,ROLE_CLIENT] }
        - { path: ^/client/*, role: ROLE_USER }
        - { path: ^/admin/*, role: ROLE_ADMIN }
        - { path: ^/api/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        
        
