# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:


    admin.partenaireassureur:
        class: Admin\AdminPartenaireAssureur
        arguments: [~, BackEnd\BrokinsBundle\Entity\PartenaireAssureur, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Partenaire Assureur }

        calls:
            - [ setTemplate, [list, BackEndBrokinsBundle:PartenaireAssureur:list.html.twig]]
        public: true


    admin.banqueassureur:
        class: Admin\AdminBanqueAssureur
        arguments: [~, BackEnd\BrokinsBundle\Entity\BanqueAssureur, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Banque Assureur }


        public: true

    admin.user:
        class: Admin\AdminUser
        arguments: [~, BackEnd\BrokinsBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: fos_user }
        public: true
    # default configuration for services in *this* file