test:
    path:     /usertest
    defaults: { _controller: BackEndBrokinsBundle:Comparatif:add }

#C'est la statistique Des Nombres de Partenaires Assureurs Dans notre Plateforme

_graphePie:
    path:     /chartPie
    defaults: { _controller: BackEndBrokinsBundle:Graphe:chartPie}


#Ce sont les routes de la partie Adresse Partenaire Assureur

ajoutadresse:
    path:     /ajout
    defaults: { _controller: BackEndBrokinsBundle:AdressePartenaireAssureur:ajout }


listeadresse:
    path:     /List
    defaults: { _controller: BackEndBrokinsBundle:AdressePartenaireAssureur:List }


reserv_s:
    path:     /supprimers/{id}
    defaults: { _controller: BackEndBrokinsBundle:AdressePartenaireAssureur:supprimers }


#Ce sont les routes de la partie Contrat

ajoutcontrat:
    path:     /AjoutContrat
    defaults: { _controller: BackEndBrokinsBundle:Contrat:ajout }


listecontrat:
    path:     /ListContrat
    defaults: { _controller: BackEndBrokinsBundle:Contrat:List }


supprimercontrat:
    path:     /SupprimerContrat/{id}
    defaults: { _controller: BackEndBrokinsBundle:Contrat:supprimers }



#Ce sont les routes de la partie Résiliation
ajoutresiliation:
    path:     /AjoutResiliation
    defaults: { _controller: BackEndBrokinsBundle:Resiliation:ajout }


listeresiliation:
    path:     /ListResiliation
    defaults: { _controller: BackEndBrokinsBundle:Resiliation:List }


supprimerresiliation:
    path:     /SupprimerResiliation/{numeroContrat}
    defaults: { _controller: BackEndBrokinsBundle:Resiliation:supprimers }

user_services :
    resource: "@BackEndBrokinsBundle/Controller/"
    type:     annotation
    prefix:   /users
    defaults:
        _format: json

fos_user_security_login:
    path:   /api/login
    defaults: { _controller: BackEndBrokinsBundle:Security:login }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_security_check:
    path:     /api/login_check
    defaults: { _controller: BackEndBrokinsBundle:Security:check }

fos_user_security_logout:
    path:     /logout
    defaults: { _controller: BackEndBrokinsBundle:Security:logout }
    methods: [GET]
