test:
    path:     /usertest
    defaults: { _controller: BackEndBrokinsBundle:Comparatif:add }

user_services :
    resource: "@BackEndBrokinsBundle/Controller/"
    type:     annotation
    prefix:   /
    defaults:
        _format: json

fos_user_security_login:
    path:   /login
    defaults: { _controller: BackEndBrokinsBundle:Security:login }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

api_fos_user_security_check:
    path:     /login_check
    defaults: { _controller: BackEndBrokinsBundle:Security:check }

fos_user_security_logout:
    path:     /logout
    defaults: { _controller: BackEndBrokinsBundle:Security:logout }
    methods: [GET]