back_end_brokins_homepage:
    path:     /admintest
    defaults: { _controller: BackEndBrokinsBundle:Default:index }

test:
    path:     /usertest
    defaults: { _controller: BackEndBrokinsBundle:Comparatif:add }

login:
    path:     /login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

brokins_ws_authentification :
    type: rest
    resource: "BackEndBrokinsBundle:WebServices/WSUser"
    prefix: api_