services:
#    back_end_brokins.example:
#        class: BackEnd\BrokinsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    redirect.after.login:
        class: BackEnd\BrokinsBundle\Redirection\AfterLoginRedirection
        arguments: ["@router"]




parameters:
    security.authentication.success_handler.class: BackEnd\BrokinsBundle\OverSf2\Security\Http\Authentication\AuthenticationSuccessHandler
